// Server-side only — never import in client components
import { existsSync, readFileSync } from "fs";
import { resolve } from "path";

const WC_BASE = `${process.env.WP_URL}/wp-json/wc/v3`;

function authHeader(): string {
  const token = Buffer.from(
    `${process.env.WC_CONSUMER_KEY}:${process.env.WC_CONSUMER_SECRET}`
  ).toString("base64");
  return `Basic ${token}`;
}

// ── Types ──────────────────────────────────────────────────────────────────────

export interface WCImage {
  id: number;
  src: string;
  alt: string;
}

export interface WCCategory {
  id: number;
  name: string;
  slug: string;
  description: string;
  image: WCImage | null;
  count: number;
  parent: number;
}

export interface WCProduct {
  id: number;
  name: string;
  slug: string;
  description: string;
  short_description: string;
  description_en: string;
  featured: boolean;
  images: WCImage[];
  categories: Array<{ id: number; name: string; slug: string }>;
  attributes: Array<{ id: number; name: string; options: string[] }>;
  related_ids: number[];
  sku: string;
  status: string;
}

// ── Build-time JSON data ────────────────────────────────────────────────────────
// Generated by scripts/generate-search-index.mjs (prebuild). When present, ALL
// API functions read from this in-memory data instead of making network requests.
// This prevents parallel Next.js worker threads from overloading WooCommerce.

let _cats: WCCategory[] | null = null;
let _prods: WCProduct[] | null = null;
let _loaded = false;

function loadBuildData() {
  if (_loaded) return;
  _loaded = true;
  try {
    const catPath = resolve(process.cwd(), "src/data/wc-categories.json");
    const prodPath = resolve(process.cwd(), "src/data/wc-products.json");
    if (existsSync(catPath)) _cats = JSON.parse(readFileSync(catPath, "utf-8"));
    if (existsSync(prodPath)) _prods = JSON.parse(readFileSync(prodPath, "utf-8"));
    if (_cats || _prods) console.log("[wc] Using prebuild JSON data");
  } catch {
    // fall through to live API
  }
}

// ── Live API client (used only when JSON is absent) ────────────────────────────

const requestCache = new Map<string, Promise<any>>();

async function wc<T>(
  endpoint: string,
  params?: Record<string, string | number>
): Promise<T> {
  const url = new URL(`${WC_BASE}${endpoint}`);
  if (params) {
    Object.entries(params).forEach(([k, v]) =>
      url.searchParams.set(k, String(v))
    );
  }
  const urlStr = url.toString();

  if (requestCache.has(urlStr)) {
    return requestCache.get(urlStr) as Promise<T>;
  }

  const promise = (async () => {
    let lastErr: unknown;
    for (let attempt = 0; attempt < 3; attempt++) {
      try {
        if (attempt > 0) await new Promise(r => setTimeout(r, attempt * 2000));
        const res = await fetch(urlStr, {
          headers: {
            Authorization: authHeader(),
            "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
          },
          signal: AbortSignal.timeout(25000),
          cache: "no-store",
        });
        if (!res.ok) throw new Error(`WC API ${res.status}: ${endpoint}`);
        return await res.json();
      } catch (e) {
        lastErr = e;
      }
    }
    throw lastErr;
  })();

  requestCache.set(urlStr, promise);
  promise.catch(() => { requestCache.delete(urlStr); });

  return promise as Promise<T>;
}

// ── Category queries ───────────────────────────────────────────────────────────

export async function getCategories(opts?: {
  per_page?: number;
  parent?: number;
  hide_empty?: boolean;
}): Promise<WCCategory[]> {
  loadBuildData();
  if (_cats !== null) {
    let result = [..._cats];
    if (opts?.hide_empty) result = result.filter((c) => c.count > 0);
    if (opts?.parent !== undefined) result = result.filter((c) => c.parent === opts.parent);
    return result;
  }
  return wc<WCCategory[]>("/products/categories", {
    per_page: opts?.per_page ?? 100,
    hide_empty: opts?.hide_empty ?? true ? 1 : 0,
    ...(opts?.parent !== undefined ? { parent: opts.parent } : {}),
    orderby: "name",
    order: "asc",
  });
}

export async function getCategoryBySlug(
  slug: string
): Promise<WCCategory | null> {
  loadBuildData();
  if (_cats !== null) {
    return _cats.find((c) => c.slug === slug) ?? null;
  }
  const cats = await wc<WCCategory[]>("/products/categories", { slug });
  return cats[0] ?? null;
}

// ── Product queries ────────────────────────────────────────────────────────────

export async function getProducts(opts?: {
  per_page?: number;
  page?: number;
  category?: number;
  featured?: boolean;
  orderby?: string;
  order?: string;
  search?: string;
  fields?: string;
}): Promise<WCProduct[]> {
  loadBuildData();
  if (_prods !== null) {
    let result = [..._prods];
    if (opts?.category !== undefined)
      result = result.filter((p) => p.categories.some((c) => c.id === opts.category));
    if (opts?.featured) result = result.filter((p) => p.featured);
    if (opts?.search) {
      const q = opts.search.toLowerCase();
      result = result.filter((p) => p.name.toLowerCase().includes(q));
    }
    // Apply ordering
    const order = opts?.order ?? "desc";
    if ((opts?.orderby ?? "date") === "date") {
      result = order === "asc" ? result.reverse() : result;
    }
    // Apply pagination
    const per_page = opts?.per_page ?? 12;
    const page = opts?.page ?? 1;
    return result.slice((page - 1) * per_page, page * per_page);
  }
  return wc<WCProduct[]>("/products", {
    per_page: opts?.per_page ?? 12,
    page: opts?.page ?? 1,
    status: "publish",
    ...(opts?.category !== undefined ? { category: opts.category } : {}),
    ...(opts?.featured ? { featured: 1 } : {}),
    ...(opts?.search ? { search: opts.search } : {}),
    ...(opts?.fields ? { _fields: opts.fields } : {}),
    orderby: opts?.orderby ?? "date",
    order: opts?.order ?? "desc",
  });
}

export async function getProductBySlug(
  slug: string
): Promise<WCProduct | null> {
  loadBuildData();
  if (_prods !== null) {
    return _prods.find((p) => p.slug === slug) ?? null;
  }
  const products = await wc<WCProduct[]>("/products", { slug, status: "publish" });
  return products[0] ?? null;
}

export async function getProductById(id: number): Promise<WCProduct | null> {
  loadBuildData();
  if (_prods !== null) {
    return _prods.find((p) => p.id === id) ?? null;
  }
  try {
    return await wc<WCProduct>(`/products/${id}`);
  } catch {
    return null;
  }
}

export async function getRelatedProducts(
  ids: number[]
): Promise<WCProduct[]> {
  if (ids.length === 0) return [];
  loadBuildData();
  if (_prods !== null) {
    return ids.slice(0, 4).map((id) => _prods!.find((p) => p.id === id)).filter(Boolean) as WCProduct[];
  }
  const subset = ids.slice(0, 4);
  const results = await Promise.all(subset.map((id) => getProductById(id)));
  return results.filter(Boolean) as WCProduct[];
}
